#include "glfuncs.h"

PFNGLGENBUFFERSPROC					glGenBuffers;
PFNGLDELETEBUFFERSPROC				glDeleteBuffers;
PFNGLBINDBUFFERPROC					glBindBuffer;
PFNGLBUFFERDATAPROC					glBufferData;
PFNGLGENVERTEXARRAYSPROC			glGenVertexArrays;
PFNGLDELETEVERTEXARRAYSPROC			glDeleteVertexArrays;
PFNGLBINDVERTEXARRAYPROC			glBindVertexArray;
PFNGLENABLEVERTEXATTRIBARRAYPROC	glEnableVertexAttribArray;
PFNGLDISABLEVERTEXATTRIBARRAYPROC	glDisableVertexAttribArray;
PFNGLVERTEXATTRIBPOINTERPROC		glVertexAttribPointer;
PFNGLCREATESHADERPROC				glCreateShader;
PFNGLSHADERSOURCEPROC				glShaderSource;
PFNGLCOMPILESHADERPROC				glCompileShader;
PFNGLGETSHADERIVPROC				glGetShaderiv;
PFNGLGETSHADERINFOLOGPROC			glGetShaderInfoLog;
PFNGLDELETESHADERPROC				glDeleteShader;
PFNGLCREATEPROGRAMPROC				glCreateProgram;
PFNGLATTACHSHADERPROC				glAttachShader;
PFNGLLINKPROGRAMPROC				glLinkProgram;
PFNGLGETPROGRAMIVPROC				glGetProgramiv;
PFNGLGETPROGRAMINFOLOGPROC			glGetProgramInfoLog;
PFNGLDELETEPROGRAMPROC				glDeleteProgram;
PFNGLUSEPROGRAMPROC					glUseProgram;
PFNGLUNIFORM1DPROC					glUniform1d;
PFNGLUNIFORM1DVPROC					glUniform1dv;
PFNGLUNIFORM1FPROC					glUniform1f;
PFNGLUNIFORM1FVPROC					glUniform1fv;
PFNGLUNIFORM1IPROC					glUniform1i;
PFNGLUNIFORM1IVPROC					glUniform1iv;
PFNGLUNIFORM2DPROC					glUniform2d;
PFNGLUNIFORM2DVPROC					glUniform2dv;
PFNGLUNIFORM2FPROC					glUniform2f;
PFNGLUNIFORM2FVPROC					glUniform2fv;
PFNGLUNIFORM2IPROC					glUniform2i;
PFNGLUNIFORM2IVPROC					glUniform2iv;
PFNGLUNIFORM3DPROC 					glUniform3d;
PFNGLUNIFORM3DVPROC					glUniform3dv;
PFNGLUNIFORM3FPROC					glUniform3f;
PFNGLUNIFORM3FVPROC					glUniform3fv;
PFNGLUNIFORM3IPROC					glUniform3i;
PFNGLUNIFORM3IVPROC					glUniform3iv;
PFNGLUNIFORM4DPROC					glUniform4d;
PFNGLUNIFORM4DVPROC					glUniform4dv;
PFNGLUNIFORM4FPROC					glUniform4f;
PFNGLUNIFORM4FVPROC					glUniform4fv;
PFNGLUNIFORM4IPROC					glUniform4i;
PFNGLUNIFORM4IVPROC					glUniform4iv;
PFNGLUNIFORMMATRIX4FVPROC			glUniformMatrix4fv;
PFNGLGENERATEMIPMAPPROC				glGenerateMipmap;
PFNGLGETUNIFORMLOCATIONPROC			glGetUniformLocation;
PFNGLVERTEXATTRIBDIVISORPROC		glVertexAttribDivisor;
PFNGLDRAWARRAYSINSTANCEDPROC		glDrawArraysInstanced;

void LoadGLFuncs() {
    glGenBuffers = (PFNGLGENBUFFERSPROC)(glXGetProcAddress("glGenBuffers"));
	glDeleteBuffers = (PFNGLDELETEBUFFERSPROC)(glXGetProcAddress("glDeleteBuffers"));
	glBindBuffer = (PFNGLBINDBUFFERPROC)(glXGetProcAddress("glBindBuffer"));
	glBufferData = (PFNGLBUFFERDATAPROC)(glXGetProcAddress("glBufferData"));
	glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)(glXGetProcAddress("glGenVertexArrays"));
	glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC)(glXGetProcAddress("glDeleteVertexArrays"));
	glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)(glXGetProcAddress("glBindVertexArray"));
	glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC)(glXGetProcAddress("glEnableVertexAttribArray"));
	glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC)(glXGetProcAddress("glDisableVertexAttribArray"));
	glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC)(glXGetProcAddress("glVertexAttribPointer"));
	glCreateShader = (PFNGLCREATESHADERPROC)(glXGetProcAddress("glCreateShader"));
	glShaderSource = (PFNGLSHADERSOURCEPROC)(glXGetProcAddress("glShaderSource"));
	glCompileShader = (PFNGLCOMPILESHADERPROC)(glXGetProcAddress("glCompileShader"));
	glGetShaderiv = (PFNGLGETSHADERIVPROC)(glXGetProcAddress("glGetShaderiv"));
	glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)(glXGetProcAddress("glGetShaderInfoLog"));
	glDeleteShader = (PFNGLDELETESHADERPROC)(glXGetProcAddress("glDeleteShader"));
	glCreateProgram = (PFNGLCREATEPROGRAMPROC)(glXGetProcAddress("glCreateProgram"));
	glAttachShader = (PFNGLATTACHSHADERPROC)(glXGetProcAddress("glAttachShader"));
	glLinkProgram = (PFNGLLINKPROGRAMPROC)(glXGetProcAddress("glLinkProgram"));
	glGetProgramiv = (PFNGLGETPROGRAMIVPROC)(glXGetProcAddress("glGetProgramiv"));
	glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC)(glXGetProcAddress("glGetProgramInfoLog"));
	glDeleteProgram = (PFNGLDELETEPROGRAMPROC)(glXGetProcAddress("glDeleteProgram"));
	glUseProgram = (PFNGLUSEPROGRAMPROC)(glXGetProcAddress("glUseProgram"));
	glUniform1d = (PFNGLUNIFORM1DPROC)(glXGetProcAddress("glUniform1d"));
	glUniform1dv = (PFNGLUNIFORM1DVPROC)(glXGetProcAddress("glUniform1dv"));
	glUniform1f = (PFNGLUNIFORM1FPROC)(glXGetProcAddress("glUniform1f"));
	glUniform1fv = (PFNGLUNIFORM1FVPROC)(glXGetProcAddress("glUniform1fv"));
	glUniform1i = (PFNGLUNIFORM1IPROC)(glXGetProcAddress("glUniform1i"));
	glUniform1iv = (PFNGLUNIFORM1IVPROC)(glXGetProcAddress("glUniform1iv"));
	glUniform2d = (PFNGLUNIFORM2DPROC)(glXGetProcAddress("glUniform2d"));
	glUniform2dv = (PFNGLUNIFORM2DVPROC)(glXGetProcAddress("glUniform2dv"));
	glUniform2f = (PFNGLUNIFORM2FPROC)(glXGetProcAddress("glUniform2f"));
	glUniform2fv = (PFNGLUNIFORM2FVPROC)(glXGetProcAddress("glUniform2fv"));
	glUniform2i = (PFNGLUNIFORM2IPROC)(glXGetProcAddress("glUniform2i"));
	glUniform2iv = (PFNGLUNIFORM2IVPROC)(glXGetProcAddress("glUniform2iv"));
	glUniform3d = (PFNGLUNIFORM3DPROC)(glXGetProcAddress("glUniform3d"));
	glUniform3dv = (PFNGLUNIFORM3DVPROC)(glXGetProcAddress("glUniform3dv"));
	glUniform3f = (PFNGLUNIFORM3FPROC)(glXGetProcAddress("glUniform3f"));
	glUniform3fv = (PFNGLUNIFORM3FVPROC)(glXGetProcAddress("glUniform3fv"));
	glUniform3i = (PFNGLUNIFORM3IPROC)(glXGetProcAddress("glUniform3i"));
	glUniform3iv = (PFNGLUNIFORM3IVPROC)(glXGetProcAddress("glUniform3iv"));
	glUniform4d = (PFNGLUNIFORM4DPROC)(glXGetProcAddress("glUniform4d"));
	glUniform4dv = (PFNGLUNIFORM4DVPROC)(glXGetProcAddress("glUniform4dv"));
	glUniform4f = (PFNGLUNIFORM4FPROC)(glXGetProcAddress("glUniform4f"));
	glUniform4fv = (PFNGLUNIFORM4FVPROC)(glXGetProcAddress("glUniform4fv"));
	glUniform4i = (PFNGLUNIFORM4IPROC)(glXGetProcAddress("glUniform4i"));
	glUniform4iv = (PFNGLUNIFORM4IVPROC)(glXGetProcAddress("glUniform4iv"));
	glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)(glXGetProcAddress("glUniformMatrix4fv"));
	glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)(glXGetProcAddress("glGenerateMipmap"));
	glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC)(glXGetProcAddress("glGetUniformLocation"));
	glVertexAttribDivisor = (PFNGLVERTEXATTRIBDIVISORPROC)(glXGetProcAddress("glVertexAttribDivisor"));
	glDrawArraysInstanced = (PFNGLDRAWARRAYSINSTANCEDPROC)(glXGetProcAddress("glDrawArraysInstanced"));
}